name: Translate Documentation

on:
  push:
    paths:
      - "docs/Fr/**"

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "Workflow lancé !"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: python --version

      - run: python scripts/translate.py